module.exports = {
    "id": "widget-apple-calendar-2",
    "x": 5,
    "y": 0,
    "w": 3,
    "h": 3,
    "lock_ratio": true,
    "content": "<style>@font-face{font-family:'WCal';src:url('/fonts/SFNS.ttf') format('truetype');font-weight:100 900;}.wcal{width:100%;height:100%;border-radius:inherit;font-family:'WCal',-apple-system,system-ui,sans-serif;overflow:hidden;box-sizing:border-box;container-type:size;container-name:wcal;display:flex;flex-direction:column;padding:10.7% 7.6% 10.1%;}.wcal-month{font-size:7cqmin;font-weight:600;color:#FD3B31;text-transform:uppercase;letter-spacing:0.03em;padding-left:1.5cqmin;margin-bottom:3.5cqmin;}.wcal-grid{flex:1;display:flex;flex-direction:column;justify-content:space-between;}.wcal-row{display:flex;flex-direction:row;justify-content:space-between;align-items:center;}.wcal-cell{display:flex;align-items:center;justify-content:center;width:calc(100%/7);font-size:6.3cqmin;font-weight:600;color:#1c1c1e;aspect-ratio:1;}.wcal-cell.hdr{font-size:5.9cqmin;font-weight:600;color:#1c1c1e;opacity:0.5;}.wcal-cell.wknd{color:#8A898E;}.wcal-cell.hdr.wknd{color:#8A898E;opacity:0.65;}.wcal-cell.today>span{width:11.4cqmin;height:11.4cqmin;border-radius:50%;background:#FD3B31;display:flex;align-items:center;justify-content:center;color:#fff;font-size:6.3cqmin;font-weight:600;}</style><div class='wcal' id='wcal'></div><script>(function(){if(window._wcalInit)return;window._wcalInit=true;var MON=['January','February','March','April','May','June','July','August','September','October','November','December'],DAY=['M','T','W','T','F','S','S'];function build(){var now=new Date(),td=now.getDate(),tm=now.getMonth(),ty=now.getFullYear(),root=document.getElementById('wcal');root.innerHTML='';var mEl=document.createElement('div');mEl.className='wcal-month';mEl.textContent=MON[tm];root.appendChild(mEl);var grid=document.createElement('div');grid.className='wcal-grid';root.appendChild(grid);var hRow=document.createElement('div');hRow.className='wcal-row';DAY.forEach(function(d,i){var c=document.createElement('div');c.className='wcal-cell hdr'+(i>=5?' wknd':'');c.textContent=d;hRow.appendChild(c);});grid.appendChild(hRow);var fd=new Date(ty,tm,1).getDay(),sc=(fd+6)%7,dm=new Date(ty,tm+1,0).getDate(),rows=Math.ceil((sc+dm)/7);for(var r=0;r<rows;r++){var row=document.createElement('div');row.className='wcal-row';for(var c=0;c<7;c++){var dn=r*7+c-sc+1,cell=document.createElement('div'),wknd=c>=5,isToday=dn===td;cell.className='wcal-cell'+(wknd?' wknd':'')+(isToday?' today':'');if(dn>=1&&dn<=dm){var s=document.createElement('span');s.textContent=dn;cell.appendChild(s);}row.appendChild(cell);}grid.appendChild(row);}}build();var n=new Date();setTimeout(function(){build();setInterval(build,86400000);},+new Date(n.getFullYear(),n.getMonth(),n.getDate()+1)-n);})();</script>",
    "css": "background-color: #ffffff; border-radius: min(22px, 14cqmin); box-shadow: 0 10px 40px rgba(0,0,0,0.25), inset 0 0.5px 0 rgba(255,255,255,0.9); border: 0.5px solid rgba(0,0,0,0.06);"
};