module.exports = {
    "id": "widget-apple-pomodoro",
    "x": 5,
    "y": 0,
    "w": 6,
    "h": 6,
    "lock_ratio": true,
    "content": "<style>.widget-pomodoro{cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;height:100%;width:100%;padding:5cqmin 6cqmin 4cqmin;box-sizing:border-box;font-family:'SF Pro Text',-apple-system,BlinkMacSystemFont,sans-serif;gap:0;transition:color 0.3s ease;}.widget-pomodoro .pomodoro-header{display:flex;align-items:center;gap:1.6cqmin;margin-bottom:0.8cqmin;}.widget-pomodoro .pomodoro-icon svg{width:8.3cqmin;height:8.3cqmin;display:block;}.widget-pomodoro .pomodoro-label{font-size:7.6cqmin;font-weight:700;text-transform:uppercase;letter-spacing:0.04em;color:rgba(255,255,255,0.62);}.widget-pomodoro .pomodoro-time{font-family:'SFRounded','SF Pro Rounded',ui-rounded,system-ui,sans-serif;font-size:29cqmin;font-weight:800;line-height:1.03;letter-spacing:-0.03em;margin-top:auto;margin-bottom:auto;}</style><div class='widget-pomodoro' onclick='window.togglePomodoro(this)'><div class='pomodoro-header'><span class='pomodoro-icon'><svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='13' r='8'></circle><line x1='12' y1='9' x2='12' y2='13'></line><line x1='12' y1='5' x2='12' y2='3'></line><line x1='9' y1='3' x2='15' y2='3'></line></svg></span><span class='pomodoro-label'>POMODORO</span></div><div class='pomodoro-time'>25:00</div></div><script>(function(){if(window._applePomodoroInit)return;window._applePomodoroInit=true;window._pomodoros=window._pomodoros||{};window.togglePomodoro=function(el){var id=el.getAttribute('data-pomo-id');if(!id){id='pomo_'+Math.random().toString(36).substr(2,9);el.setAttribute('data-pomo-id',id);window._pomodoros[id]={remaining:25*60,running:false};}var state=window._pomodoros[id];state.running=!state.running;if(state.running&&state.remaining<=0){state.remaining=25*60;}if(state.running){el.style.color='#ff9f0a';}else{el.style.color='';}updateDisplay(el,state);};function updateDisplay(el,state){var m=Math.floor(state.remaining/60);var s=state.remaining%60;var timeEl=el.querySelector('.pomodoro-time');if(timeEl){timeEl.textContent=(m<10?'0':'')+m+':'+(s<10?'0':'')+s;}}function tickPomodoros(){var widgets=document.querySelectorAll('.widget-pomodoro');widgets.forEach(function(el){var id=el.getAttribute('data-pomo-id');if(id&&window._pomodoros[id]){var state=window._pomodoros[id];if(state.running){state.remaining--;if(state.remaining<=0){state.remaining=0;state.running=false;el.style.color='#ff453a';}updateDisplay(el,state);}}});}setInterval(tickPomodoros,1000);})();</script>",
    "css": "background-color: rgba(200,220,255,0.12); backdrop-filter: blur(50px); -webkit-backdrop-filter: blur(50px); color: #ffffff; border-radius: min(28px, 15cqmin); box-shadow: 0 4px 16px rgba(0,0,0,0.15); border: 1px solid rgba(255,255,255,0.18); font-family: 'SF Pro Text', -apple-system, BlinkMacSystemFont, sans-serif;"
};