module.exports = {
    "id": "widget-google-calendar",
    "x": 13,
    "y": 4,
    "w": 5,
    "h": 5,
    "content": "<style>.gcal{width:100%;height:100%;box-sizing:border-box;display:flex;flex-direction:column;font-family:'SF Pro Text',-apple-system,BlinkMacSystemFont,sans-serif;color:inherit;overflow:hidden;container-type:size;container-name:gcalc;}.gcal-header{display:flex;align-items:center;gap:2.5cqmin;padding:4cqmin 5cqmin 2.5cqmin;flex-shrink:0;}.gcal-icon{width:7cqmin;height:7cqmin;flex-shrink:0;opacity:0.85;}.gcal-title{font-weight:700;font-size:5.5cqmin;letter-spacing:-0.02em;line-height:1;}.gcal-frame-wrap{flex:1;min-height:0;padding:0 3cqmin 3cqmin;box-sizing:border-box;}.gcal-frame{width:100%;height:100%;border:none;border-radius:3cqmin;background:transparent;display:block;filter:invert(1) hue-rotate(180deg);}.gcal-loading{flex:1;display:flex;align-items:center;justify-content:center;color:rgba(255,255,255,0.4);font-size:3.5cqmin;}</style><div class='gcal' id='gcal-root'><div class='gcal-header'><svg class='gcal-icon' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'><rect x='3' y='4' width='18' height='17' rx='3' stroke='currentColor' stroke-width='1.6' fill='none'/><path d='M3 9h18' stroke='currentColor' stroke-width='1.6' stroke-linecap='round'/><path d='M8 2v4M16 2v4' stroke='currentColor' stroke-width='1.6' stroke-linecap='round'/><rect x='7' y='13' width='2.5' height='2.5' rx='0.5' fill='currentColor' opacity='0.7'/><rect x='10.75' y='13' width='2.5' height='2.5' rx='0.5' fill='currentColor' opacity='0.7'/><rect x='14.5' y='13' width='2.5' height='2.5' rx='0.5' fill='currentColor' opacity='0.7'/></svg><div class='gcal-title'>Calendar</div></div><div class='gcal-frame-wrap' id='gcal-frame-wrap'><div class='gcal-loading' id='gcal-loading'>Loading\u2026</div></div></div><script>(function(){if(window._gcalInit)return;window._gcalInit=true;var wrap=document.getElementById('gcal-frame-wrap');var loading=document.getElementById('gcal-loading');fetch('/api/google_cal_url').then(function(r){return r.json();}).then(function(d){if(!d.url){loading.textContent='\u26a0\ufe0f Calendar not configured';return;}loading.remove();var f=document.createElement('iframe');f.className='gcal-frame';f.src=d.url;f.scrolling='no';f.frameBorder='0';wrap.appendChild(f);var container=document.getElementById('gcal-root').closest('[data-refresh]');var ms=(container?parseInt(container.dataset.refresh,10):900)*1000;setInterval(function(){f.src=d.url;},ms);}).catch(function(){loading.textContent='\u26a0\ufe0f Unavailable';});})();</script>",
    "css": "background-color: rgba(128,128,128,0.15); backdrop-filter: blur(40px); -webkit-backdrop-filter: blur(40px); color: #ffffff; border-radius: min(28px, 15cqmin); box-shadow: 0 4px 16px rgba(0,0,0,0.15); border: 1px solid rgba(255,255,255,0.18); font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif;"
};
